# Generated by Django 5.0.7 on 2024-07-17 14:06

from django.db import migrations, models
import django.utils.timezone

def get_current_time():
    return django.utils.timezone.now()

def forwards_func(apps, schema_editor):
    Post = apps.get_model('viewer', 'Post')
    Album = apps.get_model('viewer', 'Album')
    for post in Post.objects.all():
        album, created = Album.objects.get_or_create(title='Default Album')
        post.album = album
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='album',
            field=models.ForeignKey(to='viewer.Album', on_delete=models.CASCADE, related_name='photos', default=None),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func),
    ]
