# Generated by Django 5.0.7 on 2024-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='Default content'),
            preserve_default=False,
        ),
    ]
