# Generated by Django 5.0.7 on 2024-07-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_upload_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_upload',
            field=models.BooleanField(default=True),
        ),
    ]
