# Generated by Django 5.0.7 on 2024-07-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_remove_upload_title_upload_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_upload',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
